apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: <access-id-in-base64>
  AWS_ENDPOINTS: <endpoint-in-base64>
  AWS_SECRET_ACCESS_KEY: <secret-key-in-base64>
kind: Secret
metadata:
  name: longhorn-backup-secret
type: Opaque
